apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: poc-ack-policy
spec:
  name: poc-ack-policy
  policyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Action": [
                  "sns:Publish",
                  "sns:Subscribe"
              ],
              "Resource": "arn:aws:sns:us-east-1:343315438995:*"
          },
          {
              "Effect": "Allow",
              "Action": [
                  "sns:ListTopics",
                  "sns:Unsubscribe",
                  "sns:ListSubscriptions"
              ],
              "Resource": "*"
          }
      ]
    }
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: poc-ack-role
spec:
  name: poc-ack-role
  tags:
  - key: environment
    value: development
  assumeRolePolicyDocument: |
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "sns.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }
  policies:
    - arn:aws:iam::aws:policy/service-role/AmazonSNSRole
  policyRefs:
    - from:
        name: poc-ack-policy
