apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ack-sns-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ack-system
    name: in-cluster
  source:
    repoURL: public.ecr.aws/aws-controllers-k8s
    targetRevision: 1.0.6
    chart: sns-chart
    helm:
      parameters:
        - name: aws.region
          value: us-east-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
