apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ack-iam-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ack-system
    name: in-cluster
  source:
    repoURL: public.ecr.aws/aws-controllers-k8s
    targetRevision: 1.3.0
    chart: iam-chart
    helm:
      parameters:
        - name: aws.region
          value: us-east-1
        - name: aws.credentials.secretName
          value: aws-credentials
        - name: aws.credentials.secretKey
          value: credentials
        - name: aws.credentials.profile
          value: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
