apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  poc-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ack-system
    name: in-cluster
  source:
    path: resources
    repoURL: https://github.com/tiagat/aws-controllers
    targetRevision: main
    directory:
      jsonnet:
        extVars:
          - name: accountId
            value: "343315438995"
          - name: environment
            value: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
