apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ack-system
    name: in-cluster
  source:
    repoURL: public.ecr.aws/aws-controllers-k8s/s3-chart
    targetRevision: 1.0.6
    chart: s3-chart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
